apiVersion: v1
kind: Service
metadata:
  name: postgres-supertokens-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: postgres-supertokens
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

