apiVersion: apps/v1
kind: Deployment
metadata:
  name: supertokens-authentication-server
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supertokens-authentication-server
  template:
    metadata:
      labels:
        app: supertokens-authentication-server
    spec:
      containers:
      - name: supertokens-authentication-server
        image: {{ .Values.authentication_server_image }}:{{ .Values.authentication_server_version }}
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: AUTHENTICATION_SERVER_URL
          value: https://{{ .Values.host }}
        - name: FRONT_ENTRENAPP_URL
          value: https://{{ .Values.host }}
        - name: SUPERTOKENS_CORE_URL
          value: http://supertokens-core-service:3567

