apiVersion: v1
kind: Service
metadata:
  name: supertokens-core-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: supertokens-core
  ports:
    - protocol: TCP
      port: 3567
      targetPort: 3567

